apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentName }}
spec:
  type: NodePort
  ports:
  - name: flexdeployport
    port: 8080
    targetPort: 8080
    nodePort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.deploymentName }}