{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "flexdeploy-demo.serviceAccountName" . }}
  labels:
{{ include "flexdeploy-demo.labels" . | indent 4 }}
{{- end -}}
